default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ror_portfolio_1_dev_match_development
  username: postgres
  password: secret

test:
  <<: *default
  database: ror_portfolio_1_dev_match_test
  username: postgres
  password: secret

production:
  <<: *default
  database: ror_portfolio_1_dev_match_production
